kind: pipeline
name: default

trigger:
  event:
    - push

steps:
- name: "Build Docker image"
  image: plugins/docker
  environment:
    DOCKER_BUILDKIT: 1
  settings:
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    repo: quay.io/openware/wio
    tags: ${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
